services:
  teslaapiweb:
    image: teslaapiweb
    build:
      context: .
      dockerfile: src/Web/TeslaApi.Web/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  dbmysql:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - dbmysqlstorage:/var/lib/mysql
  mysqladminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  dbmysqlstorage:
