services:
  teslaapiweb:
    image: teslaapiweb
    build:
      context: .
      dockerfile: src/Web/TeslaApi.Web/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
